src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=OffreRepository::class)
 */
class Offre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Name should not be empty !!")
     * @Assert\Length(
     *     min=3,
     *     max= 20,
     *     minMessage ="Name should be >=3",
     *     maxMessage ="Name should be <=20")
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @Assert\Range(
     *      min = 0,
     *      max = 100,
     *      notInRangeMessage = "You must be between {{ min }}% and {{ max }}% to enter",
     * )
     * @ORM\Column(type="integer")
     */
    private $Pourcentage;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="Offre")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPourcentage(): ?string
    {
        return $this->Pourcentage;
    }

    public function setPourcentage(string $Pourcentage): self
    {
        $this->Pourcentage = $Pourcentage;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setOffre($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getOffre() === $this) {
                $evenement->setOffre(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="choose a positive number")
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $etat;

    /**
     * @ORM\Column(type="boolean")
     */
    private $payement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Hebergement::class, cascade={"persist"})
     */
    private $hebergement;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getPayement(): ?bool
    {
        return $this->payement;
    }

    public function setPayement(bool $payement): self
    {
        $this->payement = $payement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getHebergement(): ?Hebergement
    {
        return $this->hebergement;
    }

    public function setHebergement(?Hebergement $hebergement): self
    {
        $this->hebergement = $hebergement;

        return $this;
    }




}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Hebergement;
use App\Entity\Reservation;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date',DateType::class,[
                'widget' => 'choice',
            ])
            ->add('duree')
            ->add('payement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\HebergementRepository;
use App\Repository\ReservationRepository;
use App\Repository\UserRepository;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Class ReservationController
 * @package App\Controller
 * @Route("/res", name="res")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation", name="reservation")
     */
    public function index(ReservationRepository $repository): Response
    {
        $reservations = $this->getDoctrine()
            ->getRepository(Reservation::class)
            ->findAll();
        $list1=$repository->calcul("Acceptée");
        $total1=0;
        foreach ($list1 as $row){
            $total1++;
        }
        $list2=$repository->calcul("Annulée");
        $total2=0;
        foreach ($list2 as $row){
            $total2++;
        }
        $list3=$repository->calcul("En Cours");
        $total3=0;
        foreach ($list3 as $row){
            $total3++;
        }
        $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable(
            [['Task', 'Hours per Day'],
                ['Acceptée',     $total1],
                ['Annulée',    $total2],
                ['En Cours',    $total3]
            ]
        );
        $pieChart->getOptions()->setTitle('Reservation activities');
        $pieChart->getOptions()->setHeight(500);
        $pieChart->getOptions()->setWidth(900);
        $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#009900');
        $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);

        return $this->render('reservation/index.html.twig', [
            'reservation' => $reservations,
            'piechart' => $pieChart,
        ]);
    }

    /**
     * @Route ("/reservation/Add/{idH}", name="AddReservation")
     */
    public function add(Request $request,$idH,UserRepository $repositoryUser,HebergementRepository $hebergementRepository): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $hebergement=$hebergementRepository->find($idH);
        $user=$repositoryUser->find(1);
        $reservation->setUser($user);
        $reservation->setEtat("En Cours");
        $reservation->setHebergement($hebergement);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();
            return $this->redirectToRoute('dsdhebergementyy');
        }

        return $this->render('reservation/add.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/reservation/{id}", name="reservationShow")
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }
    /**
     * @Route("/reservations/{id}", name="print")
     */
    public function print(Reservation $reservation)
    {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reservation/show.html.twig', [
            'title' => "Welcome to our PDF Test",
            'reservation' => $reservation
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);
    }
    /**
     * @Route("/{id}/edit", name="reservationEdit")
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('resreservation');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/editAcc", name="reservationEditAcc")
     */
    public function editAcc(Request $request, Reservation $reservation): Response
    {
        $reservation->setEtat("Acceptée");

            $this->getDoctrine()->getManager()->flush();


        return $this->redirectToRoute("resreservation");
    }

    /**
     * @Route("/{id}/editDec", name="reservationEditDec")
     */
    public function editDec(Request $request, Reservation $reservation): Response
    {
        $reservation->setEtat("Annulée");

        $this->getDoctrine()->getManager()->flush();


        return $this->redirectToRoute("resreservation");
    }

    /**
     * @Route("/{id}", name="reservationDelete")
     */
    public function delete(Request $request, Reservation $reservation): Response
    {

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($reservation);
        $entityManager->flush();


        return $this->redirectToRoute('resreservation');
    }
}

templates/reservation/add.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('dsdhebergementyy') }}">back to list</a>
{% endblock %}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Update') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('resreservation') }}">back to list</a>

    <a href="{{ path('reservationDelete', {'id': reservation.id}) }}">delete</a>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}User Reservation{% endblock %}

{% block body %}
    <h1>Reservation index</h1>
    <input type="text" id="search" name="search" class="form-control" placeholder="Search by ....">

    <table class="table" id="tableac">
        <thead>
        <tr>
            <th>date</th>
            <th>duree</th>
            <th>etat</th>
            <th>payement</th>
            <th>user</th>
            <th>Qr code</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservation %}
            <tr>
                <td>{{ reservation.date|date }}</td>
                <td>{{ reservation.duree }}</td>
                <td>{{ reservation.etat }}</td>
                {% if reservation.payement==false %}
                    <td> en cours </td>
                {% elseif reservation.payement==true %}
                    <td> payé </td>
                {% endif %}
                <td>{{ reservation.user.nom }} {{ reservation.user.prenom }}</td>
                <td><img width="100px" height="100px" src="{{ qr_code_data_uri('Scan Me') }}" /></td>
                <td>
                    <a class="btn btn-success" href="{{ path('resreservationEditAcc', {'id': reservation.id}) }}">Accept</a>
                    <a class="btn btn-danger" href="{{ path('resreservationEditDec', {'id': reservation.id}) }}">Decline</a>
                    <a class="btn btn-danger" href="{{ path('resreservationDelete', {'id': reservation.id}) }}">Delete</a>
                    <a class="btn btn-danger" href="{{ path('resprint', {'id': reservation.id}) }}">Print</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}

    </table>
    </tbody>
    <div id="div_chart"></div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        {{ gc_draw(piechart, 'div_chart') }}
    </script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#search').keyup(function(){
                search_table($(this).val());
            });
            function search_table(value){
                $('#tableac tbody tr').each(function(){
                    var found = 'false';
                    $(this).each(function(){
                        if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)
                        {
                            found = 'true';
                        }
                    });
                    if(found === 'true')
                    {
                        $(this).show();

                    }
                    else
                    {
                        $(this).hide();

                    }
                });
            }
        });
    </script>
{% endblock %}

templates/reservation/pdfEvent.html.twig
<html>
<center><h2> Votre reservation a l'evenement est effectue avec success </h2></center><br>
<center> <img src="{{ asset('QrCode/'~QrCode) }}" > </center><br>
{{ QrCode }}
</html>

templates/reservation/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ReservationController!{% endblock %}

{% block body %}
        <center><h2>Mr {{ user.nom }} Votre reservation a l'evenement {{ event.Nom}} est effectue avec success </h2></center><br>
    <center> <img src="{{ asset('QrCode/'~qrcode) }}" > </center><br>

    <center> <a class="btn btn-primary" href="{{ path('ShowEvenementUser')}}">Done  </a>
    <br>
        <a class="btn btn-success" href="{{ path('ShowReservation') }}">Check your reservations</a><br>
    </center>

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>date</th>
            <td>{{ reservation.date|date }}</td>
        </tr>
        <tr>
            <th>duree</th>
            <td>{{ reservation.duree }}</td>
        </tr>
        <tr>
            <th>etat</th>
            <td>{{ reservation.etat }}</td>
        </tr>
        <tr>
            <th>payement</th>
            {% if reservation.payement==false %}
                <td> en cours </td>
            {% elseif reservation.payement==true %}
                <td> payé </td>
            {% endif %}
        </tr>
        <tr>
            <th>user</th>
            <td>{{ reservation.user.nom }} {{ reservation.user.prenom }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('resreservation') }}">back to list</a>

    <a href="{{ path('resreservationEdit', {'id': reservation.id}) }}">edit</a>

    <a href="{{ path('resreservationDelete', {'id': reservation.id}) }}">delete</a>
{% endblock %}

templates/reservation/verif.html.twig
{% if result==true %}
<center><h1>Bienvnue Mr {{ user.nom }}</h1></center>
{% else %}
<centre><h1>Ce Personne N'a pas Reservé</h1></centre>
{% endif %}